name: Pages Pipeline

on:
  push:
    branches: [master]

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/pages.jar

  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: docker build . -t pages:pipeline

      - uses: Azure/container-scan@v0
        with:
          image-name: pages:piepline

      - uses: Azure/docker-login@v1
        with:
          login-server: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push pages:pipeline

  deploy-to-cluster:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Kubectl
        run: |
          sudo apt-get update
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: EKS Login
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name dees-cloud
          kubectl config get-contexts
          kubectl apply -f deployment/pages-namespace.yaml
          kubectl apply -f deployment/pages-config.yaml
          kubectl apply -f deployment/pages-service.yaml
          kubectl apply -f deployment/pages-deployment.yaml